# Generated by Django 5.2.1 on 2025-06-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_status_listing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('fashion', 'Fashion & Accessories'), ('home', 'Home & Kitchen'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('books', 'Books & Magazines'), ('toys', 'Toys & Games'), ('phones', 'Smartphones'), ('computers', 'Computers & Laptops'), ('gaming', 'Gaming & Consoles'), ('cars', 'Cars'), ('rent', 'Apartments for Rent'), ('freelance', 'Freelancing Services'), ('collectibles', 'Collectibles'), ('misc', 'Miscellaneous')], max_length=64),
        ),
    ]
